# Generated by Django 5.2.12 on 2026-03-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livre_cree_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='livres', to='api.tag'),
        ),
    ]
